## 作業目標：運用scikit-learn API 實現K-fold分割資料

---

### 讀入資料

In [1]:
import pandas as pd
dataset = pd.read_csv(r'Social_Network_Ads.csv')

In [2]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

### 取出訓練特徵與標註

In [3]:
X = dataset[['User ID', 'Gender', 'Age', 'EstimatedSalary']].values
Y = dataset['Purchased'].values

---

In [4]:
import numpy as np
from sklearn.model_selection import KFold

### 將訓練資料按照順序切割成10等分

In [5]:

kf = KFold(n_splits=10, shuffle=False)
kf.get_n_splits(X)

print(kf)


KFold(n_splits=10, random_state=None, shuffle=False)


### 將訓練資料隨機切割成10等分

In [7]:
kf = KFold(n_splits=10, shuffle=True)
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=None, shuffle=True)


---

### 取出 切割資料對應位置

In [8]:
train_split = kf.split(X)
next(train_split)

(array([  0,   1,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  15,
         18,  19,  20,  21,  23,  24,  25,  26,  27,  28,  29,  30,  31,
         32,  33,  34,  35,  37,  39,  40,  41,  42,  43,  44,  45,  46,
         47,  48,  49,  50,  51,  53,  54,  56,  57,  58,  59,  60,  61,
         62,  63,  64,  66,  67,  69,  70,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 148, 149, 150, 152, 153, 155, 156, 157, 158, 160,
        161, 162, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
        175, 176, 178, 180, 182, 183, 184, 185, 186, 187, 188, 189, 190,
        191, 192, 193, 194, 195, 196, 197, 198, 199

### Or

In [9]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [  0   1   2   3   4   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  22  23  24  25  26  27  28  29  30  31  33  34  35  36  37  38
  40  41  42  43  45  46  47  48  49  50  51  53  54  55  56  57  58  59
  60  61  62  64  65  66  67  68  69  70  71  72  73  74  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  91  92  93  96  97  98  99 100
 101 102 103 104 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 135 136 137 138
 139 140 141 142 143 144 146 147 148 149 150 151 153 154 156 157 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 174 176 178 179 180 181
 182 183 186 187 188 189 190 191 192 193 194 195 196 198 199 200 201 202
 203 204 205 206 207 209 210 211 212 213 214 215 216 218 219 220 221 222
 223 224 225 226 227 228 229 230 232 233 234 235 237 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 255 256 257 258 259 260 261 263
 264 265 266 267 268 269 270 271 272 273 274

### 取出切割資料：trainset / testset 特徵(x_train/x_test)/標註(y_train/y_test)

In [11]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]

In [12]:
X_train

array([[15624510, 'Male', 19.0, 19000.0],
       [15810944, 'Male', 35.0, 20000.0],
       [15668575, 'Female', 26.0, 43000.0],
       ...,
       [15691863, 'Female', 46.0, 41000.0],
       [15755018, 'Male', 36.0, 33000.0],
       [15594041, 'Female', 49.0, 36000.0]], dtype=object)

In [13]:
X_test

array([[15570769, 'Female', 26.0, 80000.0],
       [15599081, 'Female', 45.0, 22000.0],
       [15689425, 'Male', 30.0, 49000.0],
       [15776348, 'Female', 27.0, 54000.0],
       [15807481, 'Male', 28.0, 79000.0],
       [15654574, 'Female', 23.0, 82000.0],
       [15595917, 'Male', 30.0, 80000.0],
       [15668385, 'Male', 39.0, 42000.0],
       [15636428, 'Female', 30.0, 116000.0],
       [15697997, 'Female', 38.0, 80000.0],
       [15773447, 'Male', 37.0, 55000.0],
       [15697020, 'Female', 39.0, 61000.0],
       [15638963, 'Female', 21.0, 68000.0],
       [15783029, 'Male', 30.0, 89000.0],
       [15605327, 'Male', 40.0, 47000.0],
       [15602373, 'Male', 29.0, 75000.0],
       [15759066, 'Female', 33.0, 60000.0],
       [15738448, 'Female', 30.0, 79000.0],
       [15735549, 'Female', 39.0, 134000.0],
       [15809347, 'Female', 41.0, 71000.0],
       [15779529, 'Female', 60.0, 108000.0],
       [15584320, 'Female', 37.0, 146000.0],
       [15750056, 'Female', 52.0, 90000.0],
